[tox]
envlist = py39,py310,py311,py312

[testenv]
deps =
    pytest>=8.1.1
    pytest-cov>=5.0.0
    pytest-mock>=3.14.0
    pytest-asyncio>=0.23.0
    respx>=0.22.0
commands =
    pytest --cov=pyetrade --cov-report=term-missing --cov-report=xml tests/
